### ISSUE TITLE
This is trash

### ISSUE THREAD

**Issue by carlpaton** [carlpaton/MouseWiggle#3]
This is trash, @klevinlaughs

**Comment by klevinlaughs** [comment]
wow 3rd issue already, must be trash

**Comment by carlpaton** [comment]
1 and 2 were super rubbish :D

![Wat](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYwDpeOK6Gpf4CNYpyu5cUvz2x1fMEMbZwBHP6XtE4vA&s)
